#------------------------------------------------------------------------------#
#                  Hurdle Truncated Log-Normal (HTLN) Model                    #
#------------------------------------------------------------------------------#

#' Hurdle Truncated Log-Normal (HTLN) Family
#'
#' Functions to fit, evaluate, and simulate from a hurdle model where the
#' continuous component follows a truncated normal distribution on the
#' log-transformed scale \eqn{Z = \log(Y + 1)}.
#'
#' This model is designed for non-negative data with excess zeros and heavy
#' right tails—common in microbiome and NGS applications—where the distribution
#' of strictly positive values is well captured by a truncated normal on the
#' log1p scale.
#'
#' The model is:
#' \deqn{
#'   P(Y = 0) = \phi, \qquad
#'   Z = \log(Y+1), \qquad
#'   Z \mid (Y > 0) \sim \mathrm{TruncNorm}(\mu, \sigma^2; [a_{\log}, b_{\log}]),
#' }
#' where:
#' * \eqn{\phi} is the hurdle probability (probability of observing a structural zero),
#' * \eqn{Z = \log(Y+1)} is truncated to the interval \eqn{[a_{\log}, b_{\log}]},
#' * \eqn{\mu} and \eqn{\sigma} are the mean and standard deviation of the
#'   truncated normal on the log scale.
#'
#' @section Fitting:
#' \code{mle_htln()} performs maximum likelihood estimation of the hurdle
#' parameter \eqn{\phi} and the truncated normal parameters \eqn{\mu} and
#' \eqn{\sigma} using numerical optimisation via \code{\link[stats]{optim}}.
#'
#' The optimisation step for the continuous component can be tuned via the
#' arguments \code{optim_method}, \code{optim_control}, \code{optim_hessian},
#' \code{optim_lower}, and \code{optim_upper}; see \code{\link[stats]{optim}}
#' for further details on these options.
#'
#' The upper truncation bound \code{b_log} applies on the log1p scale and can be:
#' \itemize{
#'   \item a numeric scalar (constant upper bound, possibly \code{Inf});
#'   \item a function of the positive log-values, e.g.
#'     \code{function(z) max(z) + 3 * sd(z)} (default).
#' }
#'
#' The function returns an object of class \code{"htln_fit"}, for which S3
#' generics \code{coef()}, \code{logLik()}, \code{AIC()}, \code{BIC()}, and
#' \code{nobs()} are implemented.
#'
#' @param y Numeric vector of non-negative observations (input to
#'   \code{mle_htln()}). Internally transformed via \code{log1p(y)}.
#' @param x Numeric vector at which to evaluate the density \code{dhtln()}
#'   (values must be on the \eqn{Z = \log(Y+1)} scale).
#' @param p Numeric vector of probabilities for \code{qhtln()}.
#' @param n Integer number of observations to simulate in \code{rhtln()}.
#' @param phi Hurdle probability \eqn{P(Y = 0)}.
#' @param meanlog,sdlog Mean and standard deviation of the truncated normal
#'   component on the log1p scale.
#' @param a_log,b_log Lower and upper truncation bounds for the truncated normal
#'   component on the log1p scale.
#' @param integer Logical. If \code{TRUE} (default), random variates generated by
#'   \code{rhtln()} are returned on the original scale and coerced to integers.
#' @param optim_method,optim_control,optim_hessian,optim_lower,optim_upper
#'   Optimisation settings used only by \code{mle_htln()} and passed directly
#'   to \code{\link[stats]{optim}} (as \code{method}, \code{control},
#'   \code{hessian}, and box constraints via \code{lower}/\code{upper}).
#'   See \code{\link[stats]{optim}} for details.
#'
#' @return
#' \itemize{
#'   \item \code{mle_htln()} returns an object of class \code{"htln_fit"} with:
#'     \itemize{
#'       \item \code{coef}: named vector with estimates \code{phi},
#'             \code{meanlog}, \code{sdlog}, and \code{b_log};
#'       \item \code{logLik}: the maximised log-likelihood;
#'       \item \code{nobs}: number of observations;
#'       \item \code{optim_trunc}: the \code{optim()} output for the continuous component.
#'     }
#'   \item \code{dhtln()} returns density values for the mixture model:
#'         a point mass \code{phi} at \eqn{Z = 0} and a truncated normal
#'         density for \eqn{Z > 0}.
#'   \item \code{qhtln()} returns quantiles on the original \eqn{Y} scale.
#'   \item \code{rhtln()} generates random samples from the fitted
#'         hurdle truncated log-normal model.
#' }
#'
#' @seealso
#'   \code{\link[stats]{optim}},
#'   \code{\link[truncnorm]{dtruncnorm}},
#'   \code{\link[truncnorm]{qtruncnorm}},
#'   \code{\link[truncnorm]{rtruncnorm}}
#'
#' @aliases
#'   mle_htln
#'   dhtln
#'   qhtln
#'   rhtln
#'
#' @importFrom stats nobs logLik AIC BIC 
#'
#' @name htln
NULL




